name: Deploy Infrastructure with Terraform

on: [push]

jobs:
  build-dev-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
  
    - name: configure Terraform cloudcredentials
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or your AWS region

    - name: Terraform Init S3 and godaddy cert
      run: terraform init
      working-directory: ./terraform/s3-cert

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/s3-cert

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/s3-cert
    
    - name: Deploy to S3
      run: aws s3 sync . s3://www.humza-resume.com --exclude "*.git*" --exclude "*.github*" --exclude "*.terraform*" --exclude "main.tf" --exclude "*.yml"
        # Additional commands for CDN cache invalidation, if needed
    
    - name: Print Instructions
      run: |
        echo "Please ensure DNS validation records are added to your domain provider before approving the continuation of the workflow. Check the Terraform output for specific DNS records that need to be added. Manual approval will be required in the 'deploy-cloudfront' job to continue with the deployment."
  
  build-dev-2:
    needs: build-dev-1
    runs-on: ubuntu-latest
    environment:  # Define the environment that requires a manual approval.
      name: prod
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
  
    - name: configure Terraform cloudcredentials
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or your AWS region

    - name: Terraform Init cloudfront
      run: terraform init
      working-directory: ./terraform/cloudfront

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/cloudfront

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/cloudfront
    
    - name: Terraform Destroy
      run: terraform destory
      