name: Deploy Infrastructure with Terraform

on: [push]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
  
    - name: configure Terraform cloudcredentials
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_CLOUD_API_TOKEN }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or your AWS region

    - name: Terraform Init S3 and godaddy cert
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="domain_name=www.humza-resume.com"
    
    - name: Empty S3 Bucket
      run: aws s3 rm s3://www.humza-resume.com --recursive
    
    - name: Deploy to S3
      run: aws s3 sync . s3://www.humza-resume.com --exclude "*.git*" --exclude "*.github*" --exclude "*.terraform*" --exclude "main.tf" --exclude "*.yml"
        
    - name: Empty S3 Bucket
      run: aws s3 rm s3://www.humza-resume.com --recursive

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
    
  
      